"""empty message

Revision ID: ddc14fa8e828
Revises: 22916e28251a
Create Date: 2025-05-10 08:58:45.407786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc14fa8e828'
down_revision = '22916e28251a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login_ip', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('current_login_ip', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('login_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('login_count')
        batch_op.drop_column('current_login_ip')
        batch_op.drop_column('last_login_ip')
        batch_op.drop_column('current_login_at')
        batch_op.drop_column('last_login_at')

    # ### end Alembic commands ###
